import "./globals.css";
import NavbarComponent from "./components/Navbar";
import { Providers } from "./providers";
import Footer
  from "./components/Footer";

export const metadata = {
  title: "Medius App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased`}
      >

        <Providers>
          <NavbarComponent />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
